# Generated by Django 6.0.6 on 2026-06-05 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('tunis', 'Tunis'), ('sfax', 'Sfax'), ('sousse', 'Sousse'), ('bizerte', 'Bizerte'), ('gabes', 'Gabès'), ('ariana', 'Ariana'), ('other', 'Other')], default='tunis', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['school', 'grade'], name='earlywarnin_school_fab444_idx'), models.Index(fields=['region'], name='earlywarnin_region_9d8323_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('explanation', models.TextField()),
                ('computed_at', models.DateField()),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='earlywarning.student')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('follow_up', 'Follow-Up'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='earlywarning.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_login', 'User Login'), ('student_created', 'Student Created'), ('student_updated', 'Student Updated'), ('student_deleted', 'Student Deleted'), ('absence_recorded', 'Absence Recorded'), ('risk_computed', 'Risk Computed'), ('alert_created', 'Alert Created'), ('intervention_created', 'Intervention Created'), ('intervention_updated', 'Intervention Updated'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('reminder_sent', 'Reminder Sent'), ('bulk_upload', 'Bulk Upload'), ('bulk_upload_failed', 'Bulk Upload Failed'), ('report_exported', 'Report Exported')], max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], default='success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='earlywarning.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='earlywarning.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('justified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='earlywarning.student')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'date'], name='earlywarnin_student_10d8ba_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
